criaCartao('assets/Versopergunta1.png', 'assets/26.png', 'assets/R26.png',  0)
criaCartao('assets/Versopergunta2.png', 'assets/27.png', 'assets/R27.png', 1)
criaCartao('assets/Versopergunta1.png', 'assets/28.png', 'assets/R28.png', 2)
criaCartao('assets/Versopergunta2.png', 'assets/29.png', 'assets/R29.png', 3)
criaCartao('assets/Versopergunta1.png', 'assets/30.png', 'assets/R30.png', 4)
criaCartao('assets/Versopergunta2.png', 'assets/31.png', 'assets/R31.png',5)
criaCartao('assets/Versopergunta1.png', 'assets/32.png', 'assets/R32.png',6)
criaCartao('assets/Versopergunta2.png', 'assets/33.png', 'assets/R33.png',7)
criaCartao('assets/Versopergunta1.png', 'assets/34.png', 'assets/R34.png',8)
criaCartao('assets/Versopergunta2.png', 'assets/35.png', 'assets/R35.png',9)
criaCartao('assets/Versopergunta1.png', 'assets/36.png', 'assets/R36.png',10)
criaCartao('assets/Versopergunta2.png', 'assets/37.png', 'assets/R37.png',11)
criaCartao('assets/Versopergunta1.png', 'assets/38.png', 'assets/R38.png',12)
criaCartao('assets/Versopergunta2.png', 'assets/39.png', 'assets/R39.png',13)
criaCartao('assets/Versopergunta1.png', 'assets/40.png', 'assets/R40.png',14)
criaCartao('assets/Versopergunta2.png', 'assets/41.png', 'assets/R41.png',15)
criaCartao('assets/Versopergunta1.png', 'assets/42.png', 'assets/R42.png',16)
criaCartao('assets/Versopergunta2.png', 'assets/43.png', 'assets/R43.png',17)
criaCartao('assets/Versopergunta1.png', 'assets/44.png', 'assets/R44.png',18)
criaCartao('assets/Versopergunta2.png', 'assets/45.png', 'assets/R45.png',19)
criaCartao('assets/Versopergunta1.png', 'assets/46.png', 'assets/R46.png',20)
criaCartao('assets/Versopergunta2.png', 'assets/47.png', 'assets/R47.png',21)
criaCartao('assets/Versopergunta1.png', 'assets/48.png', 'assets/R48.png',22)
criaCartao('assets/Versopergunta2.png', 'assets/49.png', 'assets/R49.png',23)
criaCartao('assets/Versopergunta1.png', 'assets/50.png', 'assets/R50.png',24)
